import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import styles from 'styles/Home.module.css'
import BasicLayout from "layout/Basic"
import {Helmet} from "react-helmet";
import PhoneInput from "../components/PhoneInput";
import React, {useState} from "react";
import {Checkbox} from "../components/CheckBox";




const Title = styled.h1`
  text-align: left;
  font-style: normal;
  font-weight: 700;
  font-size: 36px;
  line-height: 110%;
  color: #414141;
  margin-bottom: 45px;
  width: 358px;
`

const FlexWrapper = styled.div`
  width: 358px;
  display: flex;
  margin-top: 16px;
`

const TextContent = styled.span`
  font-style: normal;
  font-weight: 400;
  font-size: 13px;
  line-height: 120%;
  margin-left: 12px;
  color: #414141;
`



const Home: NextPage = () => {

    const [checked, setChecked] = useState(false);
    const [codeValue, setCodeValue] = useState('');

    const handleCheckboxChange = () => {
        setChecked(!checked)
        console.log('checked')
    }



  return (
      <BasicLayout>
              <Helmet>
                  <title>Create Next App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />

                  <link rel="preconnect" href="https://fonts.googleapis.com"/>
                      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                          <link href="https://fonts.googleapis.com/css2?family=Viaoda+Libre&display=swap"
                                rel="stylesheet"/>
                          </Helmet>



                      <main className={styles.main}>
                          <Title>Войти или создать
                              профиль</Title>

                        <PhoneInput checked={checked} codeValue={codeValue} setValue={setCodeValue}/>
                          <FlexWrapper onClick={handleCheckboxChange} >
                              <Checkbox checked={checked} onChange={() => console.log('Changed')}/>
                              <TextContent>При входе в аккаунт, я соглашаюсь с политикой конфиденциальности</TextContent>
                          </FlexWrapper>




                      </main>
      </BasicLayout>
  )
}

export default Home
